# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb392e3fdd9fc5986eccc7e17b1acee57c2dcdee71ff9edbcf50d44a8d548d074eaf02ae753c68eef62ec58ab3b549f413f2ea5c06c797ee82cf29c8a1c36cf0

test:
  secret_key_base: f1200c40808416193b63d79952d80e6731c8d70d9ed407a096a98d2c173f81f9397b8342d589dfc514f2b8c22056100dab4aacbdfb30ef74322d508812bd741f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
